export default [
  {
    key: "night",
    name: "Glittering Sky",
    tag: "Background",
    price: 25000,
    link: "https://c.tenor.com/L_tg3foVXJ0AAAAC/sky-aesthetic.gif",
  },
  {
    key: "street",
    name: "Eerie Sky",
    tag: "Background",
    price: 25000,
    link: "https://i.pinimg.com/originals/3d/7c/f1/3d7cf1a66b0293b2379cf5fe1368214b.png",
  },
  {
    key: "night-clouds",
    name: "Night Sky",
    tag: "Background",
    price: 25000,
    link: "https://www.gifcen.com/wp-content/uploads/2021/12/night-sky-gif-9.gif",
  },
  {
    key: "day-sky",
    name: "Day Sky",
    tag: "Background",
    price: 25000,
    link: "https://i.pinimg.com/originals/9b/82/8d/9b828d24dc90491eb8b33a2077ef70e1.gif",
  },
  {
    key: "feathers",
    name: "Feathers in Sky",
    tag: "Background",
    price: 25000,
    link: "https://i.pinimg.com/originals/3c/34/1c/3c341c7e85cd0da74b03145bf4937133.gif",
  },
  {
    key: "space",
    name: "Outer Space",
    tag: "Background",
    price: 25000,
    link: "https://data.whicdn.com/images/316556667/original.gif",
  },
  {
    key: "pixilated-sky",
    name: "Pixilated Night Sky",
    tag: "Background",
    price: 25000,
    link: "https://i.gifer.com/SJPC.gif",
  },
  {
    key: "ocean-sky",
    name: "Streets",
    tag: "Background",
    price: 25000,
    link: "https://c.tenor.com/i8Zwtt2WQsMAAAAC/city-night.gif",
  },
  {
    key: "cartoon-sky",
    name: "Cartoon Night Sky",
    tag: "Background",
    price: 25000,
    link: "https://i.gifer.com/U51u.gif",
  },
  {
    key: "onepiece-sky",
    name: "Sailing Through the Ocean",
    tag: "Background",
    price: 25000,
    link: "https://animesher.com/orig/0/55/551/5517/animesher.com_straw-hat-pirates-anime-gif-one-piece-551731.gif",
  },
  {
    key: "luffy",
    name: "Luffy",
    tag: "Background",
    price: 25000,
    link: "https://c.tenor.com/MX7na3cgJYwAAAAC/one-piece-luffy.gif",
  },
  {
    key: "yourlieinapril",
    name: "Our Symphony",
    tag: "Background",
    price: 25000,
    link: "https://giffiles.alphacoders.com/790/79041.gif",
  },
];
